Fixed some issues in the dev/prod

diff --git a/local/Dockerfile b/local/Dockerfile
--- a/local/Dockerfile
+++ b/local/Dockerfile
@@ -1,6 +1,6 @@
 # MIT License
 #
-# Copyright (c) 2023 Istituto Italiano di Tecnoogia
+# Copyright (c) 2025 Istituto Italiano di Tecnoogia
 #                    Author: Davide De Tommaso (davide.detommaso@iit.it)
 #                    Project: Dockyman Template
 #
@@ -23,108 +23,102 @@
 # SOFTWARE.
 
 ARG DOCKER_SRC=ubuntu:latest
-
 FROM ${DOCKER_SRC}
+
 LABEL maintainer="Davide De Tommaso <davide.detommaso@iit.it>"
 LABEL version="local"
 
 ENV DEBIAN_FRONTEND=noninteractive
 
 USER root
-
 WORKDIR /workdir
 
+# Install basic tools depending on distro
 RUN if [ -f /etc/alpine-release ]; then \
-        apk update; \
-        apk add sudo bash shadow; \
+        apk update && apk add sudo bash shadow; \
     elif [ -f /etc/debian_version ]; then \
-        apt-get update; \
-        apt-get install -y sudo bash; \
+        apt-get update && apt-get install -y sudo bash; \
     elif [ -f /etc/redhat-release ]; then \
-        yum update; \
-        yum install -y sudo bash shadow; \
+        yum update -y && yum install -y sudo bash shadow; \
     elif [ -f /etc/arch-release ]; then \
-        pacman -Syy; \
-        pacman -S --noconfirm sudo bash shadow; \
+        pacman -Syy && pacman -S --noconfirm sudo bash shadow; \
     else \
-        echo "Unknown distribution"; \
-        exit 1; \
+        echo "Unsupported distribution" && exit 1; \
     fi
 
+# Args and ENV
+ARG USERNAME
 ARG USER_UID
 ARG USER_GID
-ARG USERNAME
-ARG USER_GROUPS
-ARG GROUP_IDS
+ARG USER_GROUPS      # ex: "sudo,audio,video,input,dialout"
+ARG GROUP_IDS        # ex: "27,29,44,104,20"
 
+ENV USERNAME=$USERNAME
 ENV USER_UID=$USER_UID
 ENV USER_GID=$USER_GID
-ENV USERNAME=$USERNAME
 ENV USER_GROUPS=$USER_GROUPS
 ENV GROUP_IDS=$GROUP_IDS
 
-# Use bash as the shell for RUN commands
 SHELL ["/bin/bash", "-c"]
 
-# Step 2: Loop through the arrays to create or modify groups
-RUN IFS=',' read -ra groups_array <<< "$USER_GROUPS" && \
-    IFS=',' read -ra ids_array <<< "$GROUP_IDS"; \
-    for index in "${!groups_array[@]}"; do \
-        group="${groups_array[index]}"; \
-        gid="${ids_array[index]}"; \
-        printf "Group: %s, GID: %s\n" "$group" "$gid"; \
-        if getent group "$group" >/dev/null; then \
-            groupmod -o "$group" --gid "$gid"; \
-        else \
-            groupadd "$group" --gid "$gid"; \
+# Crea o rinomina i gruppi, mappando USER_GROUPS con GROUP_IDS
+RUN IFS=',' read -ra group_names <<< "$USER_GROUPS"; \
+    IFS=',' read -ra group_ids <<< "$GROUP_IDS"; \
+    for i in "${!group_names[@]}"; do \
+        gname="${group_names[$i]}"; \
+        gid="${group_ids[$i]}"; \
+        existing_group=$(getent group "$gid" | cut -d: -f1); \
+        if [ -n "$existing_group" ] && [ "$existing_group" != "$gname" ]; then \
+            echo "Renaming group $existing_group (GID=$gid) to $gname"; \
+            groupmod -n "$gname" "$existing_group"; \
+        elif ! getent group "$gname" >/dev/null; then \
+            echo "Creating group $gname with GID=$gid"; \
+            groupadd -g "$gid" "$gname"; \
         fi; \
     done
 
-# Add this line to create the group if it doesn't exist
-RUN groupadd -g "$USER_GID" "$USERNAME" || true
-
-# Check if the user exists
-RUN if id "$USERNAME" >/dev/null 2>&1; then \
-        echo "User exists"; \
-        if [ "$USER_UID" != "$(id -u $USERNAME)" ]; then \
-            echo "Changing UID to $USER_UID"; \
-            usermod -u "$USER_UID" "$USERNAME"; \
-        fi; \
-        if [ "$USER_GID" != "$(id -g $USERNAME)" ]; then \
-            echo "Changing GID to $USER_GID"; \
-            usermod -g "$USER_GID" "$USERNAME"; \
-        fi; \
-        passwd -d "$USERNAME"; \
-    else \
-        # Create the user if it doesn't exist
-        echo "User does not exist"; \
-        useradd --no-log-init -m -d "/home/$USERNAME" -u "$USER_UID" -g "$USER_GID" "$USERNAME"; \
-        passwd -d "$USERNAME"; \
+# Gestione gruppo principale (GID)
+RUN existing_group=$(getent group "$USER_GID" | cut -d: -f1); \
+    if [ -n "$existing_group" ] && [ "$existing_group" != "$USERNAME" ]; then \
+        echo "Renaming group $existing_group (GID=$USER_GID) to $USERNAME"; \
+        groupmod -n "$USERNAME" "$existing_group"; \
+    elif ! getent group "$USERNAME" >/dev/null; then \
+        groupadd -g "$USER_GID" "$USERNAME"; \
     fi
 
-# Step 4: Set user shell and home directory ownership
-RUN usermod -ms /bin/bash -d "/home/$USERNAME" "$USERNAME" && \
-    chown -R "$USER_UID:$USER_GID" "/home/$USERNAME"
+# Gestione utente
+RUN existing_user=$(getent passwd "$USER_UID" | cut -d: -f1); \
+    if [ -n "$existing_user" ] && [ "$existing_user" != "$USERNAME" ]; then \
+        echo "Renaming user $existing_user (UID=$USER_UID) to $USERNAME"; \
+        usermod -l "$USERNAME" "$existing_user"; \
+        usermod -d "/home/$USERNAME" -m "$USERNAME"; \
+        usermod -u "$USER_UID" "$USERNAME"; \
+        usermod -g "$USER_GID" "$USERNAME"; \
+    elif ! id "$USERNAME" >/dev/null 2>&1; then \
+        echo "Creating user $USERNAME"; \
+        useradd --no-log-init -m -d "/home/$USERNAME" -u "$USER_UID" -g "$USER_GID" -s /bin/bash "$USERNAME"; \
+    fi && \
+    passwd -d "$USERNAME"
 
-# Step 5: Check if "sudo" group is in the list and modify sudoers if necessary
-RUN IFS=',' read -ra groups_array <<< "$USER_GROUPS" && \
-    if [[ " ${groups_array[*]} " =~ " sudo " ]]; then \
-        echo "$USERNAME ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/$USERNAME"; \
+# Aggiunge l'utente ai gruppi secondari
+RUN IFS=',' read -ra group_names <<< "$USER_GROUPS"; \
+    for g in "${group_names[@]}"; do \
+        usermod -aG "$g" "$USERNAME"; \
+    done
+
+# Sudo senza password se serve
+RUN if echo "$USER_GROUPS" | grep -qw "sudo"; then \
+        echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$USERNAME"; \
         chmod 0440 "/etc/sudoers.d/$USERNAME"; \
     fi
 
-# Step 6: Add the user to additional groups specified by GROUP_IDS
-RUN IFS=',' read -ra group_names <<< "$GROUP_IDS" && \
-    for group_name in "${group_names[@]}"; do \
-        if getent group "$group_name" >/dev/null; then \
-            usermod -a -G "$group_name" "$(getent passwd "$USER_UID" | cut -d: -f1)"; \
-        fi; \
-    done
-
+# Cleanup
 RUN rm -f /var/log/lastlog /var/log/faillog /var/log/dpkg.log
 
+# PATH update
 ENV PATH=${PATH}:/home/${USERNAME}/.local/bin:/workdir
 
 RUN touch /.Xauthority && chmod 600 /.Xauthority
 
 USER $USERNAME
+
